### ISSUE TITLE
Hello, can the results of detection, semantic segmentation, lane lines, etc. be displayed on the bird's eye view? Where can I modify it?

### ISSUE THREAD

**Issue by PlutoXN** [bharath5673/yolov5_BEV#1]
Hello, can the results of detection, semantic segmentation, lane lines, etc. be displayed on the bird's eye view? Where can I modify it?

**Comment by bharath5673** [comment]
try this [https://github.com/bharath5673/OpenVINO-ADAS](https://github.com/bharath5673/OpenVINO-ADAS)
