### ISSUE TITLE
Object Detection works but getting blank outputs for transformed and simulated image

### ISSUE THREAD

**Issue by ananya-ayasi** [bharath5673/yolov5_BEV#2]
I tested it on a similar video, the object detection is working correctly but the transformed image is just blank.

https://github.com/bharath5673/yolov5_BEV/assets/62476858/71bad931-f164-4e1d-9c75-ab26368f0d73

**Comment by HHIR** [comment]
> I tested it on a similar video, the object detection is working correctly but the transformed image is just blank.
> 
>  output_yolo.mp4

I have same issue. have you fix it in some how ?

**Comment by ananya-ayasi** [comment]
Set tracking= True
